#!/bin/bash

# we know that this script is called for:
# 1) generating plain chain spec
# 2) generating raw chain spec
# => let's see if `--raw` argument is passed and do what we need to do

PLAIN_CHAIN_SPEC=
RUNTIME_WASM_BLOB=
RAW_CHAIN_SPEC_REQUIRED=

echo "args: $@" >>/tmp/my

while test $# -gt 0
do
    case "$1" in
        --raw)
            RAW_CHAIN_SPEC_REQUIRED=1
            ;;
        --chain)
            shift
            PLAIN_CHAIN_SPEC=$1
            ;;
        --runtime-wasm-blob)
            shift
            RUNTIME_WASM_BLOB=$1
            ;;
    esac
    shift
done

if [ -z "$PLAIN_CHAIN_SPEC" ]; then
    echo "Invalid arguments"
    exit 1
fi

if [ -z "$RAW_CHAIN_SPEC_REQUIRED" ]; then
    cat $PLAIN_CHAIN_SPEC
else
    TMP_PATCH=`mktemp`
    TMP_RAW=`mktemp`
    TMP_RAW1=`mktemp`
    TMP_ERR=`mktemp`

    # default specification (generated by runtime) is for a custom live network and zombienet
    # has already generated keystore files for local network
    ORIGINAL_NAME=`cat $PLAIN_CHAIN_SPEC | jq --compact-output --monochrome-output --join-output '.name'`
    ORIGINAL_ID=`cat $PLAIN_CHAIN_SPEC | jq --compact-output --monochrome-output --join-output '.id'`
    ORIGINAL_TYPE=`cat $PLAIN_CHAIN_SPEC | jq --compact-output --monochrome-output --join-output '.chainType'`
echo $ORIGINAL_NAME >>/tmp/my222
cat $PLAIN_CHAIN_SPEC >/tmp/plain
    #echo $TMP_FILE
    # we are only patching default chain spec, so we need to cut everything else
    cat $PLAIN_CHAIN_SPEC | jq --compact-output --monochrome-output --join-output '.genesis.runtime' >$TMP_PATCH
$CHAIN_SPEC_BUILDER_PATH --chain-spec-path /tmp/plain2 runtime -r $RUNTIME_WASM_BLOB patch -p $TMP_PATCH 2>$TMP_ERR
    # ok, let's generate default chain spec + patch it
    $CHAIN_SPEC_BUILDER_PATH --chain-spec-path $TMP_RAW runtime -s -r $RUNTIME_WASM_BLOB patch -p $TMP_PATCH 2>$TMP_ERR
    if [ $? -eq 0 ]; then
cat $TMP_RAW | jq ".name = \"$ORIGINAL_NAME\" | .id = \"$ORIGINAL_ID\" | .chainType = \"$ORIGINAL_TYPE\"" >/tmp/raw4 2>&1
        # restore original chain id, name and type
        cat $TMP_RAW | jq ".name = \"$ORIGINAL_NAME\" | .id = \"$ORIGINAL_ID\" | .chainType = \"$ORIGINAL_TYPE\"" >$TMP_RAW1
cat $TMP_RAW1 >/tmp/raw3
        cat $TMP_RAW1
    else
cat "bad" >/tmp/raw3
        cat $TMP_ERR
    fi
fi
