[package]
name = "bridge-hub-polkadot-runtime-constants"
repository.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[features]
default = [ "std" ]
std = []
