#!/bin/bash

# import common functions
source "$FRAMEWORK_PATH/utils/bridges.sh"

# Expected sovereign accounts.
#
# Generated by:
#
#[test]
#fn generate_sovereign_accounts() {
#	use polkadot_parachain_primitives::primitives::Sibling;
#	use sp_core::crypto::Ss58Codec;
#
#	parameter_types! {
#		pub UniversalLocationPongPolkadot: InteriorLocation = [GlobalConsensus(Polkadot), Parachain(5000)].into();
#		pub UniversalLocationPingKusama: InteriorLocation = [GlobalConsensus(Kusama), Parachain(5000)].into();
#	}
#
#
#	println!(
#		"GLOBAL_CONSENSUS_POLKADOT_SOVEREIGN_ACCOUNT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			xcm_builder::GlobalConsensusConvertsFor::<UniversalLocationPingKusama, [u8; 32]>::convert_location(
#				&Location { parents: 2, interior: [GlobalConsensus(Polkadot)].into() }
#			)
#			.unwrap()
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#	println!(
#		"PING_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			SiblingParachainConvertsVia::<Sibling, [u8; 32]>::convert_location(&Location {
#				parents: 1,
#				interior: [Parachain(5000)].into()
#			})
#			.unwrap()
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#
#	println!(
#		"GLOBAL_CONSENSUS_KUSAMA_SOVEREIGN_ACCOUNT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			xcm_builder::GlobalConsensusConvertsFor::<UniversalLocationPongPolkadot, [u8; 32]>::convert_location(
#				&Location { parents: 2, interior: [GlobalConsensus(Kusama)].into() }
#			)
#			.unwrap()
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#	println!(
#		"PONG_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			SiblingParachainConvertsVia::<Sibling, [u8; 32]>::convert_location(&Location {
#				parents: 1,
#				interior: [Parachain(5000)].into()
#			})
#			.unwrap()
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#}
GLOBAL_CONSENSUS_POLKADOT_SOVEREIGN_ACCOUNT="FxqimVubBRPqJ8kTwb3wL7G4q645hEkBEnXPyttLsTrFc5Q"
PING_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA="FBeL7DvEGWKyKcqZBERyd7EkuF4HSyigDzdKdZ1tqfQBD9E"
GLOBAL_CONSENSUS_KUSAMA_SOVEREIGN_ACCOUNT="14zcUAhP5XypiFQWA3b1AnGKrhZqR4XWUo4deWkwuN5y983G"
PONG_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT="13cKp897TgksfCouk7UPDpaPTvxUB5igJLtN6GGQy8URciJV"

# Expected sovereign accounts for rewards on BridgeHubs.
#
# Generated by:
##[test]
#fn generate_sovereign_accounts_for_rewards() {
#	use bp_messages::LaneId;
#	use bp_relayers::{PayRewardFromAccount, RewardsAccountOwner, RewardsAccountParams};
#	use sp_core::crypto::Ss58Codec;
#
#	println!(
#		"ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhks",
#				RewardsAccountOwner::ThisChain
#			))
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#
#	println!(
#		"ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhks",
#				RewardsAccountOwner::BridgedChain
#			))
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#
#
#	println!(
#		"ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhpd",
#				RewardsAccountOwner::ThisChain
#			))
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#	println!(
#		"ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhpd",
#				RewardsAccountOwner::BridgedChain
#			))
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#}
#ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain="13E5fui93Uyua5RtDv2LQj4aVBBHo6YREe3n6CBwYdqNqoxj"
#ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain="13E5fui93Uyua5RtDv2c9kcAbfrVFeeHyJzHe8sn1Ti77Afd"
#ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain="EoQBtnwp4jMtCEpV7C88rKrz6x1qMBh2z74ibGSqtZRnuMM"
#ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain="EoQBtnwp4jMtCEpV7CPsssT6bdDHuHZmf3aGXxHJiSA4Dz3"

LANE_ID="00000002"
XCM_VERSION=3

AHK_DOT_ED=10000000
DOT=10000000000

AHP_KSM_ED=10000000
KSM=1000000000000

function init_polkadot_kusama() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path init-bridge polkadot-to-bridge-hub-kusama \
	--source-host localhost \
	--source-port 9942 \
	--source-version-mode Auto \
	--target-host localhost \
	--target-port 8945 \
	--target-version-mode Auto \
	--target-signer //Alice
}

function init_kusama_polkadot() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path init-bridge kusama-to-bridge-hub-polkadot \
        --source-host localhost \
        --source-port 9945 \
        --source-version-mode Auto \
        --target-host localhost \
        --target-port 8943 \
        --target-version-mode Auto \
        --target-signer //Alice
}

function run_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers-and-messages bridge-hub-kusama-bridge-hub-polkadot \
        --polkadot-host localhost \
        --polkadot-port 9942 \
        --polkadot-version-mode Auto \
        --bridge-hub-polkadot-host localhost \
        --bridge-hub-polkadot-port 8943 \
        --bridge-hub-polkadot-version-mode Auto \
        --bridge-hub-polkadot-signer //Charlie \
        --bridge-hub-polkadot-transactions-mortality 4 \
        --kusama-host localhost \
        --kusama-port 9945 \
        --kusama-version-mode Auto \
        --bridge-hub-kusama-host localhost \
        --bridge-hub-kusama-port 8945 \
        --bridge-hub-kusama-version-mode Auto \
        --bridge-hub-kusama-signer //Charlie \
        --bridge-hub-kusama-transactions-mortality 4 \
        --lane "${LANE_ID}"
}

case "$1" in
  run-relay)
    init_kusama_polkadot
    init_polkadot_kusama
    run_relay
    ;;
  init-asset-hub-polkadot-local)
      ensure_polkadot_js_api
      # HRMP
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 5000 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          5000 1002 4 524288
      # set XCM version of remote PingKusama
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          5000 \
          "ws://127.0.0.1:9913" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 5000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bridge-hub-polkadot-local)
      ensure_polkadot_js_api
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$PONG_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT" \
          $((250 * $DOT))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain" \
          $((250 * $DOT))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery confirmation
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain" \
          $((250 * $DOT))
      # set XCM version of remote BridgeHubKusama
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8943" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      # set XCM version of sibling PongPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8943" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 5000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-asset-hub-kusama-local)
      ensure_polkadot_js_api
      # HRMP
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 5000 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          5000 1002 4 524288
      # set XCM version of remote PongPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          5000 \
          "ws://127.0.0.1:9050" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 5000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bridge-hub-kusama-local)
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$PING_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA" \
          $((250 * $KSM))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain" \
          $((250 * $KSM))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery confirmation
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain" \
          $((250 * $KSM))
      # set XCM version of remote BridgeHubPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8945" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      # set XCM version of sibling PingKusama
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8945" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 5000 } ] } }')" \
          $XCM_VERSION
      ;;
  *)
    echo "A command is require. Supported commands for:
    Local (zombienet) run:
          - run-relay
          - init-asset-hub-polkadot-local
          - init-bridge-hub-polkadot-local
          - init-asset-hub-kusama-local
          - init-bridge-hub-kusama-local
          - reserve-transfer-assets-from-asset-hub-polkadot-local
          - withdraw-reserve-assets-from-asset-hub-polkadot-local
          - reserve-transfer-assets-from-asset-hub-kusama-local
          - withdraw-reserve-assets-from-asset-hub-kusama-local";
    exit 1
    ;;
esac
